### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by NicoRenaud** [dianna-ai/dianna#433] opened 2022-12-20 15:55 UTC
Hi Dianna, 

I'm playing with dianna for the deeprank sub-project and here is my little report so far

- I've tried to install dianna via `pip install -e . ` and that results in downloading installing at least 6 different versions of tensorflow. Since each version comes at 500 MBs I have now at least 3GBs of tensorflow.   Since I have limited space on my VM I actually ran out of disk space installing diannna. I'm not sure if this behavior is normal or if I'm doing something wrong with my conda environment. I ended up installing tf separately

- At least two packages (torchtext, spacy) are missing from the requirements.

Thanks for all the work you've done ! 🤗

**Comment by cpranav93** [comment] 2023-01-11 12:36
Hey @NicoRenaud, 

I am not able to replicate this bug. When I try to install dianna locally it installs only one version of tf (2.11.0). Which OS did you try the install? 

@geek-yang, I see that spacy gets installed for me in WSL even though it is not explicitly added as a requirement - must be a secondary requirement. However, torchtext does not get automatically installed (unless it is in .dev mode). Is that intentional?

**Comment by NicoRenaud** [comment] 2023-01-11 13:56
I'm on Ubuntu 22. It might be because my conda env was as mess. I did not try to install dianna in a clean environment.

**Comment by cpranav93** [comment] 2023-01-11 14:17
Interesting! I noticed that even with a clean conda environment, since we use pip to install dianna, it tends to pick up some residues of your base installation. It could be related to that. If you have some time and can try a clean install, do let us know if the error still occurs.

**Comment by loostrum** [comment] 2023-01-17 12:38
@NicoRenaud about the torchtext/spacy issue: which branch were you using? On the main branch (and in release 0.6.0) we have a [text] variant that install torchtext and spacy. If you don't have them, trying to use text features should give a sensible error telling you what to do. If it doesn't, let me know. 
I see the addition of the [text] variant didn't make it into the deeprank branch yet. I'll merge main into deeprank now, so it should work there as well.

**Comment by cpranav93** [comment] 2023-01-23 08:59
Closing this issue for now as the issue is not found in other installations.

**Comment by cpranav93** [comment] 2023-01-30 11:00
I faced the same issue when i create a new conda environment and try to install with pip install.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/16958416/215459268-e489bf11-a246-4827-ad3c-189d28e2a1ad.png">

**Comment by stefsmeets** [comment] 2023-02-21 15:07
I can't reproduce this on debian with python 3.8, 3.9 and 3.10, and with conda/python3.9. I get tensorflow 2.11 every single time. Also the github actions install tensorflow 2.11 correctly every time. 

I'm going to close this, because this does not seem to be an issue with dianna.

Feel free to re-open if this comes back (and post the entire pip install log!)

**Closed by stefsmeets** 2023-02-21 15:07 UTC
Labels: blocked
