### ISSUE TITLE
JOSS: address reviews

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#354] opened 2022-09-20 14:41 UTC
Address the [JOSS reviews](https://github.com/openjournals/joss-reviews/issues/4493)

**Comment by gcroci2** [comment] 2022-09-20 17:50
I opened PR #355

**Comment by egpbos** [comment] 2022-10-19 13:12
So

1. an installation instruction should be added (`pip install dianna`, basically? the reviewer says "for newbies", so maybe they also want to see that you first must install python, pip and only then install dianna?) and 
2. a "functionality" explanation should be added, so I guess a basic usage example?
3. Depending on whether sara-02 can run the tests now, something may need to be added there as well?

**Comment by cwmeijer** [comment] 2022-11-01 14:59
Outdated and duplicate of #367 .

**Closed by cwmeijer** 2022-11-01 14:59 UTC
